/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formation.graph;


import formation.DAO.SessionCoursDAO;
import formation.metier.SessionCours;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author donof
 */
public class CreaSessionCours extends javax.swing.JPanel {

    /**
     * Creates new form CreaSessionCours
     */
    SessionCoursDAO sessioncoursDAO = null;
    
    public CreaSessionCours() {
        initComponents();
    }

    public void setSessioncoursDAO(SessionCoursDAO sessioncoursDAO) {
        this.sessioncoursDAO = sessioncoursDAO;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelidsessioncours = new javax.swing.JLabel();
        txtIdsessioncours = new javax.swing.JTextField();
        labelDatedebut = new javax.swing.JLabel();
        txtDatedebut = new javax.swing.JTextField();
        labelDatefin = new javax.swing.JLabel();
        txtDatefin = new javax.swing.JTextField();
        btnCreation = new javax.swing.JButton();
        txtIdcours = new javax.swing.JTextField();
        txtIdlocal = new javax.swing.JTextField();
        labelInscrits = new javax.swing.JLabel();
        labelIdcours = new javax.swing.JLabel();
        txtNbreinscrits = new javax.swing.JTextField();
        labelIdlocal = new javax.swing.JLabel();

        labelidsessioncours.setText("Id de la session");

        txtIdsessioncours.setEditable(false);
        txtIdsessioncours.setMinimumSize(new java.awt.Dimension(50, 20));
        txtIdsessioncours.setPreferredSize(new java.awt.Dimension(150, 30));
        txtIdsessioncours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdsessioncoursActionPerformed(evt);
            }
        });

        labelDatedebut.setText("Date de début");

        labelDatefin.setText("Date de fin");

        btnCreation.setText("Créer");
        btnCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreationActionPerformed(evt);
            }
        });

        labelInscrits.setText("Nombre d'inscrits");

        labelIdcours.setText("Id du cours");

        labelIdlocal.setText("Id du local");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreation)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelidsessioncours)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelDatefin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDatedebut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelInscrits)
                            .addComponent(labelIdcours)
                            .addComponent(labelIdlocal))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdsessioncours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDatedebut)
                            .addComponent(txtDatefin)
                            .addComponent(txtIdcours)
                            .addComponent(txtIdlocal)
                            .addComponent(txtNbreinscrits))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelidsessioncours)
                            .addComponent(txtIdsessioncours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDatedebut)
                            .addComponent(txtDatedebut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(labelDatefin))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtDatefin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelInscrits)
                            .addComponent(txtNbreinscrits, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelIdcours)
                            .addComponent(txtIdcours, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(labelIdlocal))
                    .addComponent(txtIdlocal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnCreation)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdsessioncoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdsessioncoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdsessioncoursActionPerformed

    private void btnCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreationActionPerformed
        try {
            Date datedebut = Date.valueOf(txtDatedebut.getText());
            Date datefin = Date.valueOf(txtDatefin.getText());
            int nbreinscrits = Integer.parseInt(txtNbreinscrits.getText());
            int idcours = Integer.parseInt(txtIdcours.getText());
            int idlocal = Integer.parseInt(txtIdlocal.getText());
            SessionCours scrs = new SessionCours(0, datedebut,datefin,nbreinscrits,idcours,idlocal);
            scrs = sessioncoursDAO.create(scrs);
            txtIdsessioncours.setText("" + scrs.getIdsessioncours());
            JOptionPane.showMessageDialog(this, "Session de cours créé", "succès", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCreationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDatedebut;
    private javax.swing.JLabel labelDatefin;
    private javax.swing.JLabel labelIdcours;
    private javax.swing.JLabel labelIdlocal;
    private javax.swing.JLabel labelInscrits;
    private javax.swing.JLabel labelidsessioncours;
    private javax.swing.JTextField txtDatedebut;
    private javax.swing.JTextField txtDatefin;
    private javax.swing.JTextField txtIdcours;
    private javax.swing.JTextField txtIdlocal;
    private javax.swing.JTextField txtIdsessioncours;
    private javax.swing.JTextField txtNbreinscrits;
    // End of variables declaration//GEN-END:variables
}
