/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formation.graph;

import formation.DAO.SessionCoursDAO;
import formation.metier.Cours;
import formation.metier.SessionCours;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author donof
 */
public class RechSessionCours extends javax.swing.JPanel {

    /**
     * Creates new form RechSessionCours
     */
    SessionCoursDAO sessioncoursDAO = null;
    SessionCours scs = null;
    
    public RechSessionCours() {
        initComponents();
    }

    public void setSessioncoursDAO(SessionCoursDAO sessioncoursDAO) {
        this.sessioncoursDAO = sessioncoursDAO;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelidsessioncours = new javax.swing.JLabel();
        txtIdsessioncours = new javax.swing.JTextField();
        labelDatedebut = new javax.swing.JLabel();
        txtDatedebut = new javax.swing.JTextField();
        labelDatefin = new javax.swing.JLabel();
        txtDatefin = new javax.swing.JTextField();
        btnRecherche = new javax.swing.JButton();
        txtIdcours = new javax.swing.JTextField();
        txtIdlocal = new javax.swing.JTextField();
        labelInscrits = new javax.swing.JLabel();
        labelIdcours = new javax.swing.JLabel();
        txtNbreinscrits = new javax.swing.JTextField();
        labelIdlocal = new javax.swing.JLabel();
        btnMaj = new javax.swing.JButton();
        btnEffacer = new javax.swing.JButton();

        labelidsessioncours.setText("Id de la session");

        txtIdsessioncours.setMinimumSize(new java.awt.Dimension(50, 20));
        txtIdsessioncours.setPreferredSize(new java.awt.Dimension(150, 30));
        txtIdsessioncours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdsessioncoursActionPerformed(evt);
            }
        });

        labelDatedebut.setText("Date de début");

        labelDatefin.setText("Date de fin");

        btnRecherche.setText("Rechercher");
        btnRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheActionPerformed(evt);
            }
        });

        labelInscrits.setText("Nombre d'inscrits");

        labelIdcours.setText("Id du cours");

        labelIdlocal.setText("Id du local");

        btnMaj.setText("Màj");
        btnMaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMajActionPerformed(evt);
            }
        });

        btnEffacer.setText("Effacer");
        btnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelidsessioncours)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelDatefin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelDatedebut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelInscrits)
                    .addComponent(labelIdcours)
                    .addComponent(labelIdlocal)
                    .addComponent(btnRecherche))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdsessioncours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDatedebut)
                            .addComponent(txtDatefin)
                            .addComponent(txtIdcours)
                            .addComponent(txtIdlocal)
                            .addComponent(txtNbreinscrits))
                        .addContainerGap(91, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEffacer)
                        .addGap(58, 58, 58))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelidsessioncours)
                            .addComponent(txtIdsessioncours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDatedebut)
                            .addComponent(txtDatedebut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(labelDatefin))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtDatefin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelInscrits)
                            .addComponent(txtNbreinscrits, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelIdcours)
                            .addComponent(txtIdcours, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(labelIdlocal))
                    .addComponent(txtIdlocal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecherche)
                    .addComponent(btnMaj)
                    .addComponent(btnEffacer))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdsessioncoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdsessioncoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdsessioncoursActionPerformed

    private void btnRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheActionPerformed
        try {
            int idSessioncours = Integer.parseInt(txtIdsessioncours.getText());
            scs = sessioncoursDAO.read(idSessioncours);
            txtDatedebut.setText(""+scs.getDatedebut());
            txtDatefin.setText(""+scs.getDatefin());
            txtNbreinscrits.setText(""+scs.getNbreinscrits());
            txtIdcours.setText(""+scs.getIdcours());
            txtIdlocal.setText(""+scs.getIdlocal());
            JOptionPane.showMessageDialog(this, "Session de cours trouvée", "succès", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRechercheActionPerformed

    private void btnMajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMajActionPerformed
        try {
            try {
            int idSessioncours = Integer.parseInt(txtIdsessioncours.getText());
            Date datedebut = Date.valueOf(txtDatedebut.getText());
            Date datefin = Date.valueOf(txtDatefin.getText());
            int inscrits = Integer.parseInt(txtNbreinscrits.getText());
            int idcours = Integer.parseInt(txtIdcours.getText());
            int idlocal = Integer.parseInt(txtIdlocal.getText());
            scs = new SessionCours(idSessioncours,datedebut,datefin,inscrits,idcours,idlocal);
            sessioncoursDAO.update(scs);
            JOptionPane.showMessageDialog(this, "Session de cours mise à jour", "succès", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMajActionPerformed

    private void btnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerActionPerformed
        try {
            int idSessioncours = Integer.parseInt(txtIdsessioncours.getText());
            sessioncoursDAO.delete(scs);
            txtDatedebut.setText("");
            txtDatefin.setText("");
            txtNbreinscrits.setText("");
            txtIdcours.setText("");
            txtIdlocal.setText("");
            JOptionPane.showMessageDialog(this, "Session de cours effacée", "succès", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEffacerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEffacer;
    private javax.swing.JButton btnMaj;
    private javax.swing.JButton btnRecherche;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDatedebut;
    private javax.swing.JLabel labelDatefin;
    private javax.swing.JLabel labelIdcours;
    private javax.swing.JLabel labelIdlocal;
    private javax.swing.JLabel labelInscrits;
    private javax.swing.JLabel labelidsessioncours;
    private javax.swing.JTextField txtDatedebut;
    private javax.swing.JTextField txtDatefin;
    private javax.swing.JTextField txtIdcours;
    private javax.swing.JTextField txtIdlocal;
    private javax.swing.JTextField txtIdsessioncours;
    private javax.swing.JTextField txtNbreinscrits;
    // End of variables declaration//GEN-END:variables
}
